name: Build, Test and Lint .NET Project

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  schedule:
    - cron: '*/30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build with warnings as errors (StyleCop enforced)
      run: dotnet build --no-restore -warnaserror

    - name: Run tests
      run: dotnet test --no-build --verbosity normal

    - name: Lint with dotnet format (optional auto-fix check)
      run: dotnet format --verify-no-changes --severity error
