name: GPT Discussion Bot

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  check_discussions:
    runs-on: ubuntu-latest
    steps:
      - name: Call GPT manually with curl
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          prompt="Say hello from GitHub Discussions bot"
          
          response=$(curl -s https://api.openai.com/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -d '{
              "model": "gpt-4",
              "messages": [{"role": "user", "content": "'"$prompt"'"}]
            }')

          echo "$response"